/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -no-prefix Test1 test1.fst -skip-compilation -drop WasmSupport -tmpdir out
  F* version: <unknown>
  KreMLin version: 2f843633
 */

#include "Test1.h"

uint32_t _DICE_DIGEST_LENGTH = (uint32_t)0x20U;

uint32_t _DICE_UDS_LENGTH = (uint32_t)0x20U;

Prims_list__uint8_t *udslist;

#define UDS 0

typedef uint8_t uds_t_tags;

bool uu___is_UDS(uint32_t len, uint8_t *projectee)
{
  return true;
}

uint8_t *__proj__UDS__item___0(uint32_t len, uint8_t *projectee)
{
  return projectee;
}

#define CDI 0

typedef uint8_t cdi_t_tags;

bool uu___is_CDI(uint32_t len, uint8_t *projectee)
{
  return true;
}

uint8_t *__proj__CDI__item___0(uint32_t len, uint8_t *projectee)
{
  return projectee;
}

Prims_int _BIGLEN = (krml_checked_int_t)9;

uint32_t *__proj__Mkbigval_t__item__data(uint32_t *projectee)
{
  return projectee;
}

uint32_t *__proj__Mkaffine_point_t__item__x(affine_point_t projectee)
{
  return projectee.x;
}

uint32_t *__proj__Mkaffine_point_t__item__y(affine_point_t projectee)
{
  return projectee.y;
}

uint32_t *__proj__Mkaffine_point_t__item__infinity(affine_point_t projectee)
{
  return projectee.infinity;
}

uint32_t *__proj__Mkecdsa_sig_t__item__r(ecdsa_sig_t projectee)
{
  return projectee.r;
}

uint32_t *__proj__Mkecdsa_sig_t__item__s(ecdsa_sig_t projectee)
{
  return projectee.s;
}

#define RIoT_ECC_PublicKey 0

typedef uint8_t riot_ecc_publickey_tags;

bool uu___is_RIoT_ECC_PublicKey(affine_point_t projectee)
{
  return true;
}

affine_point_t __proj__RIoT_ECC_PublicKey__item___0(affine_point_t projectee)
{
  return projectee;
}

#define RIoT_ECC_PrivateKey 0

typedef uint8_t riot_ecc_privatekey_tags;

bool uu___is_RIoT_ECC_PrivateKey(ecdsa_sig_t projectee)
{
  return true;
}

ecdsa_sig_t __proj__RIoT_ECC_PrivateKey__item___0(ecdsa_sig_t projectee)
{
  return projectee;
}

#define Digest 0

typedef uint8_t digest_t_tags;

bool uu___is_Digest(uint32_t len, uint8_t *projectee)
{
  return true;
}

uint8_t *__proj__Digest__item___0(uint32_t len, uint8_t *projectee)
{
  return projectee;
}

void riotCrypto_Hash(uint32_t digestLen, uint8_t *cDigest, uint32_t cdiLen, uint8_t *cdi)
{
  
}

void riotCrypto_DeriveEccKey()
{
  
}

void riotStart(uint32_t cdiLen, uint8_t *cdi)
{
  KRML_CHECK_SIZE(sizeof (uint8_t), _DICE_DIGEST_LENGTH);
  uint8_t digest[_DICE_DIGEST_LENGTH];
  memset(digest, 0U, _DICE_DIGEST_LENGTH * sizeof digest[0U]);
  riotCrypto_Hash(_DICE_DIGEST_LENGTH, digest, cdiLen, cdi);
}

exit_code main()
{
  kremlinit_globals();
  uint8_t
  uds[32U] =
    {
      (uint8_t)0xb5U, (uint8_t)0x85U, (uint8_t)0x94U, (uint8_t)0x93U, (uint8_t)0x66U, (uint8_t)0x1eU,
      (uint8_t)0x2eU, (uint8_t)0xaeU, (uint8_t)0x96U, (uint8_t)0x77U, (uint8_t)0xc5U, (uint8_t)0x5dU,
      (uint8_t)0x59U, (uint8_t)0x0bU, (uint8_t)0x92U, (uint8_t)0x94U, (uint8_t)0xe0U, (uint8_t)0x94U,
      (uint8_t)0xabU, (uint8_t)0xafU, (uint8_t)0xd7U, (uint8_t)0x40U, (uint8_t)0x78U, (uint8_t)0x7eU,
      (uint8_t)0x05U, (uint8_t)0x0dU, (uint8_t)0xfeU, (uint8_t)0x6dU, (uint8_t)0x85U, (uint8_t)0x90U,
      (uint8_t)0x53U, (uint8_t)0xa0U
    };
  KRML_CHECK_SIZE(sizeof (uint8_t), _DICE_DIGEST_LENGTH);
  uint8_t cdi[_DICE_DIGEST_LENGTH];
  memset(cdi, 0U, _DICE_DIGEST_LENGTH * sizeof cdi[0U]);
  KRML_CHECK_SIZE(sizeof (uint8_t), _DICE_DIGEST_LENGTH);
  uint8_t uDigest[_DICE_DIGEST_LENGTH];
  memset(uDigest, 0U, _DICE_DIGEST_LENGTH * sizeof uDigest[0U]);
  KRML_CHECK_SIZE(sizeof (uint8_t), _DICE_DIGEST_LENGTH);
  uint8_t rDigest[_DICE_DIGEST_LENGTH];
  memset(rDigest, 0U, _DICE_DIGEST_LENGTH * sizeof rDigest[0U]);
  KRML_CHECK_SIZE(sizeof (uint8_t), _DICE_DIGEST_LENGTH);
  uint8_t uDigest1[_DICE_DIGEST_LENGTH];
  memset(uDigest1, 0U, _DICE_DIGEST_LENGTH * sizeof uDigest1[0U]);
  KRML_CHECK_SIZE(sizeof (uint8_t), _DICE_DIGEST_LENGTH);
  uint8_t rDigest1[_DICE_DIGEST_LENGTH];
  memset(rDigest1, 0U, _DICE_DIGEST_LENGTH * sizeof rDigest1[0U]);
  return EXIT_SUCCESS;
}

